### ISSUE TITLE
[🐛BUG] 社交推荐数据集下载以后，没有.net文件

### ISSUE THREAD

**Issue by maobohe520** [RUCAIBox/RecBole-GNN#34]
你好，我发现一个问题，使用本项目脚本下载的数据集，用于社交推荐以后，没有.net文件，请问是什么原因？
运行  python run_recbole_gnn.py -m MHCN -d lastfm

ValueError: [lastfm.net] not found in [dataset/lastfm].

**Comment by hyp1231** [comment]
感谢指出这个问题！social-aware 的方法的数据集请从 [Social-Datasets](https://github.com/Sherry-XLL/Social-Datasets) 这个项目中下载，并将下载后的数据集放在 `dataset/` 文件夹下。

我们稍后会在 README 里添加数据集下载相关的提示，thx！

**Comment by hyp1231** [comment]
由于长时间无新回复，该 issue 已关闭。如果还有疑问，欢迎随时评论。
