### ISSUE TITLE
希望支持NegSampleEvalDataLoader

### ISSUE THREAD

**Issue by zgmming** [RUCAIBox/RecBole-GNN#36]
RecBole-GNN比RecBole快很多，但是不支持负采样评估，希望支持NegSampleEvalDataLoader，可以更方便进行比较论baseline。

**Comment by hyp1231** [comment]
感谢建议！我们会添加这个功能，也欢迎您通过 PR 的方式贡献代码，使这个开源项目更加完善。

**Comment by hyp1231** [comment]
您好！我们已经在 #39 中添加了这个功能，再次感谢您的建议！
