### ISSUE TITLE
[🐛BUG] 关于lightgcn实验部分Laplace正则化的一个疑问。

### ISSUE THREAD

**Issue by sunshinelium** [RUCAIBox/RecBole-GNN#47]
**问题描述**
lightgcn源代码中对于度为0的点是设置为inf，也就是正则化后变为0，但我看咱这个实现的代码中这些度为0的节点正则化后为1，就这种差异想咨询下。

**屏幕截图**
上为当前库的实现截图，下为lightgcn中的实现
![image](https://user-images.githubusercontent.com/44607300/190554366-a8f5543d-b76f-40bd-b23e-dbeb6096d57c.png)
![image](https://user-images.githubusercontent.com/44607300/190554441-39dd4ff2-9b44-4dbd-9d02-b5fb62de03a1.png)

**Comment by hyp1231** [comment]
这里实现的代码最终返回 `edge_weight`，它根据 `edge_index` 索引 `norm_deg` 而来，而度为 0 的点不会出现在 `edge_index` 中，因此似乎无论度为 0 的点的 `norm_deg` 值为多少，似乎都不会影响返回的 `edge_weight` 变量的数值。

印象里当时这样处理主要是不希望除 0，应该是影响不大的。

**Comment by sunshinelium** [comment]
哦哦，原来是这样啊，感谢回复，了解了，谢谢啦
