### ISSUE TITLE
[💡SUG] DiffNet跑不过LightGCN

### ISSUE THREAD

**Issue by LDY911** [RUCAIBox/RecBole-GNN#48]
您好，看您的官方文档基于lastfm数据集的Evaluation Results中DiffNet跑不过LightGCN，我使用RecBole在FilmTrust和CiaoDVD数据集上的结果也是DiffNet不如LightGCN，请问这样的结果的原因是什么呢，会不会在Epinions这样的数据集上DiffNet会优于LightGCN呢，谢谢解答！

**Comment by hyp1231** [comment]
我觉得主要是 LightGCN 利用了 user 和 item 的多阶交互历史，而 DiffNet 应该是只用了 user 的一阶交互历史，item 侧则没有使用。在这种情况下，即使加入了社交网络信息，可能也没有交互历史信息更关键。因此我倾向于 Epinions 上 DiffNet 不会优于 LightGCN，不过您也可以尝试实验。

**Comment by LDY911** [comment]
> 
感谢您的回答
