### ISSUE TITLE
[🐛BUG] 在ML-100K上进行序列推荐，使用uni100评测标准报错

### ISSUE THREAD

**Issue by QwQ2000** [RUCAIBox/RecBole-GNN#50]
**描述这个 bug**
好像对于uni100这个标准的支持有点问题，非常的奇怪。不仅100K，ML-1M等等也有相同问题。

**如何复现**
1. git clone https://github.com/RUCAIBox/RecBole.git
2. cd RecBole
3. pip install -e .
4. git clone https://github.com/RUCAIBox/RecBole-GNN.git
5. cd RecBole-GNN
6. 使用官方给出的diginetica的yaml文件，session_id改成user_id，评测mode改成uni100
7. python run_recbole_gnn.py --config_files=test.yaml --dataset=ml-100k --model=SRGNN
8. 然后就可以看见各种各样奇特的错误了，我做过很多修改的尝试不过好像都不太容易解决这个问题。EvalDataloader的cat_interaction那里会报错。另外，我试过直接跑测试脚本，发现所有的序列推荐模型好像都过不了测试的样子……

**实验环境（请补全下列信息）：**
 - 操作系统: Ubuntu 22.04
- RecBole 版本 和 master branch 一样
 - Python 版本 3.9
- PyTorch 版本 1.12
- cudatoolkit 版本 11.6

**Comment by hyp1231** [comment]
因为 RecBole 几周前更新了一个大版本，目前 RecBole-GNN 还没有适配新版，如果您急用可以通过 `pip install recbole==1.0.1` 安装并使用。

我们也会尽快适配新版本，谢谢！

**Comment by QwQ2000** [comment]
问题已解决，感谢。

**Comment by hyp1231** [comment]
您好！我们刚刚适配了 RecBole 1.1.1 版本 #53，欢迎试用。同时与旧版本（RecBole 1.0.1）适配的代码也保存在 recbole1.0.1 分支下了。

**Comment by QwQ2000** [comment]
非常感谢您对本问题的关注
