### ISSUE TITLE
[🐛BUG] 关于social recommendation模型SEPT占用显存非常大的疑惑

### ISSUE THREAD

**Issue by zj13** [RUCAIBox/RecBole-GNN#55]
在yelp1数据集中跑SEPT模型，所需要的显存容量居然高于24Gb导致显存溢出，而MHCN模型只需要1GB不到的显存，这显然是不合理的，想请问下是否复现代码有错误或者是该模型确实需要非常大的显存？现在只能在小数据集lastfm上能够运行该模型。非常期待作者是否有解决该问题的建议，是否需要多张卡并行运算才能运行该模型呢？

**Comment by Sherry-XLL** [comment]
@zj13，您好，非常感谢您对 RecBole-GNN 的关注与反馈！

SEPT 模型的复现确实存在 bug，我们已经在 #56 中修复了这一问题，更新版的代码中 SEPT 模型的显存占用在合理范围内，您可以试着更新代码后重新运行该模型。

再次感谢您的反馈，后续有使用上的问题或建议欢迎继续与我们交流。

**Comment by zj13** [comment]
非常感谢您的解答！
