### ISSUE TITLE
如何指定自己的数据集

### ISSUE THREAD

**Issue by ralgond** [RUCAIBox/RecBole-GNN#60]
hi，您好：

我参照着github首页的执行如下命令：
python run_recbole_gnn.py -m [model] -d [dataset]

我想修改dataset的默认项“ml-100k”， 但是我不知道如何设置dataset项。

所以想请问下如何设置自己的数据集。

谢谢！

**Comment by hyp1231** [comment]
您好！可以参考 API 文档 [link](https://recbole.io/docs/user_guide/usage/running_new_dataset.html) 来使用自定义数据集，RecBole-GNN 和 RecBole 在这方面的设置是相同的。
