### ISSUE TITLE
关于不同数据集下超参数搜索

### ISSUE THREAD

**Issue by downeykking** [RUCAIBox/RecBole-GNN#68]
您好！在yelp20数据集下，想请教下像NGCF，LightGCN，SGL这类模型进行超参数搜索的时候，一般需要设置多少个epochs才能保证它们收敛呢

**Comment by hyp1231** [comment]
突然发现没回复这条，抱歉！我一般是默认 300 epochs，协同过滤模型一般会在 150 epochs 左右 early stop
