### ISSUE TITLE
[❓Question] 请问为什么 `sequential_base.yaml` 中 `train_neg_sample_args` 要设置为 `None`?

### ISSUE THREAD

**Issue by ChenglongMa** [RUCAIBox/RecBole-GNN#70]
请问在配置文件 `recbole_gnn/properties/quick_start_config/social_base.yaml` 中，为什么要将 `train_neg_sample_args` 设置为 `None`?

https://github.com/RUCAIBox/RecBole-GNN/blob/77d76b9e19436220b32fe61af95ffd95f17c1db7/recbole_gnn/properties/quick_start_config/sequential_base.yaml#L1

这样设置有什么特殊考虑吗？Sequential model不支持负采样吗？

谢谢！

**Comment by dst111dst** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。图片链接二维码图片

**Comment by hyp1231** [comment]
您好，sequential model 默认是使用 Cross Entropy loss 优化，并以全部其他商品作为负例的，配置文件中这样写即是代表使用全部商品作为负例优化。但是您也可以手动设置这个参数，以只采样固定个数 item 作为负例。

**Comment by ChenglongMa** [comment]
@hyp1231 好的，多谢解答！
